version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-library
    restart: unless-stopped
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPass
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_library_data:/var/lib/postgresql/data
volumes:
  postgres_library_data:
    name: postgres_library_data